In [1]:
import numpy as np

In [2]:
a = np.array([[1,4],[3,1]])

In [3]:
a

array([[1, 4],
       [3, 1]])

In [4]:
np.sort(a) 

array([[1, 4],
       [1, 3]])

In [5]:
np.sort(a, axis=None)

array([1, 1, 3, 4])

In [6]:
np.sort(a, axis=0)  

array([[1, 1],
       [3, 4]])

In [7]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]

In [8]:
dtype

[('name', 'S10'), ('height', float), ('age', int)]

In [9]:
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galahad', 1.7, 38)]

In [10]:
a = np.array(values, dtype=dtype)

In [11]:
np.sort(a, order='height') 

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [12]:
np.sort(a, order=['age', 'height'])   

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])